# 範例
***

# [教學目標]

* 知道 Pandas 的特性與貢獻
* 能夠使用 DataFrame 與 Series 當中的屬性
* 初步理解 Seies、DataFrame 與 NdArray 的比較


In [1]:
# 載入 NumPy, Pandas 套件
import numpy as np
import pandas as pd

# 檢查正確載入與版本
print(np)
print(np.__version__)
print(pd)
print(pd.__version__)

<module 'numpy' from 'D:\\anaconda3\\envs\\viz\\lib\\site-packages\\numpy\\__init__.py'>
1.20.2
<module 'pandas' from 'D:\\anaconda3\\envs\\viz\\lib\\site-packages\\pandas\\__init__.py'>
1.2.4


In [2]:
# 從 Series 和 DataFrame 開始

s = pd.Series([1, 2, 3])
print(s)
print(type(s))


0    1
1    2
2    3
dtype: int64
<class 'pandas.core.series.Series'>


In [3]:

df = pd.DataFrame([1, 2, 3])
print(df)
print(type(df))


   0
0  1
1  2
2  3
<class 'pandas.core.frame.DataFrame'>


In [4]:
# Series 的常用屬性

s = pd.Series([1, 2, 3])
print(s.shape) # (3, )
print(s.size) # 3
print(s.dtype) # int64


(3,)
3
int64


In [5]:
# DataFrame 的常用屬性

df = pd.DataFrame([1, 2, 3])
print(df.shape) # (3, 1)
print(df.size) # 3
print(df.dtypes) 


(3, 1)
3
0    int64
dtype: object


## [簡答題] 請問 Pandas 套件最主要的貢獻是什麼？

- 可讓使用者明確知道資料屬性
- 方便資料清洗、分析
- 可將資料可視化

## 根據提供的資料集，印出他們的屬性分別為何？
## （屬性：shape、size、values、根據提供的資料集，印出他們的屬性分別為何？
（屬性：shape、size、values、index、columns、dtypes、len）
、columns、dtypes、len）


In [6]:
a = np.random.rand(3,4)
df = pd.DataFrame(a)
df.columns = ["a", "b", "c", "d"]
display(df)

a         b         c         d
0  0.375733  0.473820  0.882019  0.698258
1  0.541277  0.846103  0.832595  0.171663
2  0.199139  0.513992  0.311022  0.634231

In [7]:
print(df.shape)
print(df.size)
print(df.values)
print(df.index)
print(df.columns)
print(df.dtypes)

(3, 4)
12
[[0.375733   0.47382045 0.88201926 0.69825791]
 [0.54127726 0.84610253 0.83259464 0.17166333]
 [0.19913885 0.51399204 0.31102213 0.63423107]]
RangeIndex(start=0, stop=3, step=1)
Index(['a', 'b', 'c', 'd'], dtype='object')
a    float64
b    float64
c    float64
d    float64
dtype: object
