# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

array = np.arange(1, 12, 1)
array[2:6] = -array[2:6]

In [2]:
'''
Your Code
'''
print(array)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [3]:
A = np.random.rand(3, 6)

'''
Your Code
'''
M = A.copy()
M[M > 0.5] = 1
M[M <= 0.5] = 0
print(A)
print("A > 0.5 :", int(M.sum()))

[[0.97553209 0.86137242 0.36963104 0.91282864 0.14956763 0.46497504]
 [0.24612402 0.29097503 0.45216682 0.48062712 0.12306724 0.91839285]
 [0.61185046 0.29763228 0.78164041 0.71738692 0.45892485 0.03189836]]
A > 0.5 : 7
