# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

- a為ndarray時, 可使用成員函式sum()對內容進行加總，並且可依不同軸向加總計算
- np.sum()需要輸入一個ndarray加總，同樣可依不同軸向加總計算
- sum()為python本身對list, tuple進行加總的函式，僅限元素為int 或 float

In [9]:
'''
Your Code
'''
import numpy as np
A = np.arange(11)
print(A.sum())
print(np.sum(A))
print(sum(A))

55
55
55


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [12]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [13]:
A = np.random.random((5, 5))

'''
Your Code
'''
A_mean = A.mean()
A_std = A.std()
A_norm = (A - A_mean) / A_std
print(A)
print(A_norm)

[[0.59997308 0.39975998 0.77851501 0.87904806 0.05989979]
 [0.30651612 0.61465212 0.31973471 0.64364268 0.38910646]
 [0.90871109 0.0463957  0.46754857 0.46959715 0.87017737]
 [0.64054025 0.0350523  0.73504967 0.15555102 0.84180638]
 [0.08165825 0.62966955 0.6684025  0.7319549  0.46389496]]
[[ 0.33156226 -0.40196268  0.98569005  1.35401509 -1.64711556]
 [-0.74358215  0.38534215 -0.69515294  0.49155547 -0.44099419]
 [ 1.46269217 -1.69659078 -0.15360421 -0.14609878  1.32151535]
 [ 0.48018905 -1.73814985  0.82644519 -1.29667617  1.21757198]
 [-1.56739865  0.44036184  0.58226855  0.81510681 -0.16699001]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [23]:
'''
Your Code
'''
B = np.random.randint(100, size=10)
print(B)
B_max = B.max()
B[B==B_max] = -1
print(B)

[55 71 92 40  3 64 79 80 43 60]
[55 71 -1 40  3 64 79 80 43 60]
